# Theme metadata
name = "bridges"
description = "Some theme"
license = "MIT"
homepage = "https://github.com/yourusername/zola-bridges-theme"
min_version = "0.14.0"

[extra]


# Menu items
menu = [
    { name = "Me", url = "/" },
    { name = "Reviews", url = "/Reviews" },
    { name = "Articles", url = "/articles" },
    { name = "Guestbook", url = "/guestbook" }
]
